---
- name: create tomcat group
  group:
    name: tomcat
    state: present
    
- name: create user
  user:
    name: tomcat
    comment: tomcat
    shell: /bin/false
    group: tomcat
    home: /opt/tomcat

