---
- name: creat directory
  file:
   path: /opt/tomcat
   state: directory

- name: extract the tar file
  command: sudo tar xzvf /home/maha/apache-tomcat-8.5.47.tar.gz -C /opt/tomcat --strip-components=1