---
- name: creat directory
  file:
   path: /opt/tomcat
   state: directory

- name: extract the tar file
  unarchive:
    src: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.47/bin/apache-tomcat-8.5.47.tar.gz
    dest: /opt/tomcat
    remote_src: yes