---
- name:  chgrp 
  file:
    path: /opt/tomcat
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat

- name: chmod11
  file:
    path: /opt/tomcat/conf
    state: directory
    recurse: yes
    mode: g+r

- name: chmod22
  file:
    path: /opt/tomcat/conf
    state: directory
    mode: g+x

- name: chown on webapps
  file:
    path: /opt/tomcat/webapps/
    state: directory
    recurse: yes
    owner: tomcat
- name: chown on work
  file:
    path: /opt/tomcat/work/
    state: directory
    recurse: yes
    owner: tomcat
- name: chown on temp
  file:
    path: /opt/tomcat/temp/
    state: directory
    recurse: yes
    owner: tomcat

- name: chown on logs
  file:
    path: /opt/tomcat/logs/
    state: directory
    recurse: yes
    owner: tomcat
  
  